server:
  port: 7081

spring:
  application:
    name: uniConfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/songning123456/uni-resource.git
          force-pull: true
          username: 1457065857@qq.com
          password: 772805406sn123.

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7082/eureka/ # 指定注册中心的地址，以便使用服务发现功能

logging:
  level:
    root: warn
    com: info
  file:
    name: logs/uni-config.log