server:
  port: 7081

spring:
  application:
    name: uniConfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/songning123456/uni-resource.git
          force-pull: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.109:7082/eureka/ # 指定注册中心的地址，以便使用服务发现功能
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

logging:
  level:
    root: warn
    com: info
  file:
    name: logs/uni-config.log